@startuml UsecasePhongDaoTao
' Cấu hình giao diện một chút cho đẹp'
skinparam actorStyle awesome
left to right direction

actor "Cán bộ phòng đào tạo" as User

rectangle "Hệ thống Quản lý lịch huấn luyện" {
    usecase "Quản lý thông tin tài khoản" as UC1
    usecase "Quản lý lịch huấn luyện học kỳ" as UC4
    usecase "Phê duyệt lịch phân công giảng dạy \n của các khoa theo tháng" as UC5
    usecase "Phê duyệt phiếu đề nghị thay đổi \n kế hoạch giảng dạy của các khoa" as UC6
    usecase "Trình duyệt lịch phân công giảng dạy \n tháng" as UC7
    usecase "Quản lý thông tin lớp học" as UC8
    usecase "Quan lý thông tin sinh viên" as UC9
    usecase "Quản lý thông tin phòng học" as UC10
    usecase "Quản lý nhật ký huấn luyện theo ngày" as UC11
    note right of UC1
        Cán bộ phòng đào tạo có thể đăng nhập, đăng ký, sửa đổi thông tin tài khoản của mình.
    end note
    note right of UC4
        Bao gồm các thao tác xem, nhập, sửa, xóa, gửi phê duyệt lịch huấn luyện học kỳ.
        Lịch huấn luyện học kỳ sẽ được gửi đến Phó hiệu trưởng để phê duyệt.
    end note
    note right of UC5
        Cán bộ phòng đào tạo sẽ phê duyệt hoặc từ chối lịch phân công giảng dạy tháng của các khoa.
    end note
    note right of UC6
        Cán bộ phòng đào tạo sẽ phê duyệt hoặc từ chối phiếu đề nghị thay đổi kế hoạch giảng dạy của các khoa.
    end note
    note right of UC7
        Cán bộ phòng đào tạo trình duyệt lịch phân công giảng dạy tháng của các khoa đã được phê duyệt tới Phó Hiệu Trưởng.
    end note
    note right of UC8
        Cán bộ phòng đào tạo có thể thêm, sửa, xóa thông tin lớp học.
    end note
    note right of UC9
        Cán bộ phòng đào tạo có thể thêm, sửa, xóa thông tin sinh viên.
    end note
    note right of UC10
        Cán bộ phòng đào tạo có thể thêm, sửa, xóa thông tin phòng học.
    end note
    note right of UC11
        Cán bộ phòng đào tạo nhập nhận xét đánh giá huấn luyện theo ngày.
    end note

    skinparam usecase {
        BackgroundColor #c7e11a
        BorderColor #2ec149
        FontSize 13
        FontColor #333333
    }
    skinparam note {
        BackgroundColor #f9f9f9
        BorderColor #cccccc
        FontSize 12
        FontColor #333333
    }
    skinparam actor {
        BackgroundColor #3f9f50
        BorderColor #cccccc
        FontSize 13
        FontColor #333333
    }
    skinparam rectangle {
        BackgroundColor #fff
        BorderColor #cccccc
        FontSize 14
        FontColor #333333
    }

    '     Quan hệ giữa các Use Case
    '     UC5 ..> UC6 : <<include>>
    '     UC2 --|> UC3 : (kế thừa tính năng)
    ' Quan hệ giữa Actor và Use Case'
    User -- UC1
    User -- UC4
    User -- UC5
    User -- UC6
    User -- UC7
    User -- UC8
    User -- UC9
    User -- UC10
    ' Quan hệ với hệ thống bên thứ ba
    ' UC5 -- PaymentGate
}
@enduml
